version: '3.8'
services:
  web:
    build:
      context: .
      args:
        - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
    ports:
      - "3000:3000"
    env_file:
      - .env
    network_mode: bridge